#!/bin/bash

## Polkit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

## Luz calida
#redshift -O 4250K -r -P &

## Brillo al minimo
brightnessctl s 0 &

## Portapapeles
parcellite &

## Salvapantallas
#xscreensaver -nosplash &


##----------------------------------------

## Cambios de distribucion de teclado us/latam
$HOME/.config/scripts/toggle_us_latam.sh &

## Ajuste sin DM
dbus-update-activation-environment DISPLAY &

## NumBloq Activado 
numlockx &

## Escritorio
pcmanfm --desktop &

