#!/bin/bash

## Ajuste auxiliar sin Display Manager
#dbus-update-activation-environment DISPLAY &

## Salvapantallas
#xscreensaver -nosplash &

## Luz calida
#redshift -O 4250K -r -P &

## Cambios de distribucion de teclado us/latam (ALT+SHIFT)
##$HOME/.config/scripts/toggle_us_latam.sh &


##----------------------------------------


## Resolucion lxrandr
$HOME/.config/scripts/lxrandr.sh &

## Agente de autenticación de PolicyKit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

## Depósito de claves de GNOME: Servicio de secretos
/usr/bin/gnome-keyring-daemon --start --components=secrets &

## Certificados y almacenamiento de claves
/usr/bin/gnome-keyring-daemon --start --components=pkcs11 &

## Portapapeles
parcellite &

## NumBloq Activado
numlockx &

## Brillo al minimo
brightnessctl s 0 &

## Nitrogen
nitrogen --restore &

## Generacion carpetas
xdg-user-dirs-update &

