#!/bin/bash

## 
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

## Luz calida
redshift -O 4250K -r -P &

## Brillo al minimo
brightnessctl s 0 &

## Portapapeles
parcellite &

## Restaura la ultima imagen aplicada
nitrogen --restore &

## Salvapantallas
#xscreensaver -nosplash &

## Keyring
#gnome-keyring-daemon &

##----------------------------------------

## Cambios de distribucion de teclado us/latam
$HOME/.config/scripts/toggle_us_latam.sh &

## Ajuste sin WM
dbus-update-activation-environment DISPLAY &
